[package]
name = "yak_swc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4.0"
serde = "1.0.217"
serde_json = "1.0.134"
swc_core = { version = "16.0.0", features = ["ecma_plugin_transform"] }
css_in_js_parser = { path = "../css_in_js_parser" }
relative_posix_path = { path = "../relative_posix_path" }
itertools = "0.13.0"
percent-encoding = "2.3.1"
rustc-hash = "2.1.0"

[dev-dependencies]
divan = "0.1.17"
regex = "1.10.3"
swc_ecma_transforms_testing = "11.0.1"
swc_ecma_parser = "10.0.0"
testing = "5.0.0"

[[bench]]
name = "extension_detection"
harness = false

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
